#+LaTeX_CLASS: elemica-com-article
#+TITLE: How to use this directory
#+AUTHOR: Peter Frank, Michael Kloeckner
#+DATE: 2015-10-19
#+DESCRIPTION: How toorganize files in this directory
#+EMAIL: pfrank@elemica.com
#+KEYWORDS: Elemica 2.0
#+LANGUAGE: english

* Intro

This directory contains the source and documentation of our cloud formation (cf)
configurations. It is organized on the base of Amazon Accounts (AWS accounts) and
=chef.environments=. It should be easy to identify the used cloud formation templates for a given =chef.environment=.

We use =chef.environment= to indicate the chef environment.
Where we use 'environment' if we mean any environment, be it Chef or AWS. 

The idea is to write templates, that can be shared by all AWS accounts beeing
parametrized according to environments.
 
We create cf stacks by using generalized cf templates that can be
 - used by all environments regardless of the AWS account (under aws-base-cf-templates/)
 - parametrized by environment specific parameter files (under aws-xyz/=chef.environment=/)
 - DEPRECATED used by all environments within an AWS account (under aws-abc/ref-abc) 

* First Layer: Amazon Accounts
The first layer consists of subdirectories for each AWS account and one
directory for base templates.
** AWS accounts
Naming convention: Use prefix 'aws-' to avoid mix up with =chef.environments=.
- aws-dev/ 
- aws-stg/ 
- aws-prd/ 
Within each directory you find environment specific subdirectories.

** Base templates for all AWS accounts
Directory 'aws-base-cf-templates/' contains cloud formation templates, that are *shared
by all environments in all AWS accounts*.
- aws-base-cf-templates/

* Second layer: =chef.environments=
This layer contains directories for the =chef.environments= and direcotirs for templates that are shared within
the enclosing AWS account.

** =chef.environments=
Naming convention: =chef.environments=.

Example for environment router-dublin-dev
- aws-dev/router-dublin-dev/
These directories contain cf templates that are shared by the
environments inside the specific AWS account.


=chef.environments= names are threefold, constiting of a name, the AWS region and the AWS account.

** shared within AWS accounts
*DEPRECATED*: This layer also references templates, that are shared *only in the enclosing AWS account*.
 - aws-dev/ref-dev/
 - aws-stg/ref-stg/
 - aws-prd/ref-prd/


* Third layer: parameter files.
This layer contains parameter files to configure the base templates in the first layer.

Naming convention parameter files: use base template name and replace '-template' 
with '-parameter'. 
File =cf-setup-environment-name.org= contains the documentation and CRUD commands. 

Example for the fabric autoscaling group in aws-dev chef.environment router-dublin-dev:

With two templates:
 - aws-base-cf-templates/cf-vpc-asg-base-template-v-0-0-2.json 
 - aws-dev/router-dublin-dev/cf-vpc-asg-fabric-parameter-v-0-0-2.json
we create the fabric autoscaling cf stack.






